pipeline {
    agent any
    stages {
        stage('Build Image') {
            steps {
                sh 'echo "First Step"'
            }
        }
	stage('Push Image') {
            steps {
                        withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                        	sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                        	sh 'docker push krajewskim/test:' + env.BRANCH_NAME
                        }
            }
	}
        stage('Part 2') {
            when {
              branch 'master'
            }
            steps {
                sh 'docker ps'
            }
        }
}
}
